version: '3.8'
services:
  room-server:
    build: .
    ports:
      - '6666:6666'
    environment:
      - NODE_ENV=production
    volumes:
      - ./:/app
      - /app/node_modules
    restart: unless-stopped
